version: '3'

volumes:
  backoffice_postgres_data: {}
  backoffice_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backoffice_local_django
    container_name: backoffice_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/local/.django
      - ./.envs/local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      - djangonetwork

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backoffice_production_postgres
    container_name: backoffice_local_postgres
    ports:
      - '5432:5432'
    volumes:
      - backoffice_postgres_data:/var/lib/postgresql/data
      - backoffice_postgres_data_backups:/backups
    env_file:
      - ./.envs/local/.postgres
    networks:
      - djangonetwork

  redis:
    image: redis:6
    container_name: backoffice_local_redis
    networks:
      - djangonetwork

  celeryworker:
    <<: *django
    image: backoffice_local_celeryworker
    container_name: backoffice_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A config.celery_app worker -l INFO
    networks:
      - djangonetwork

  celerybeat:
    <<: *django
    image: backoffice_local_celerybeat
    container_name: backoffice_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A config.celery_app beat -l INFO
    networks:
      - djangonetwork
    
  mq:
    image: rabbitmq:3.9.11-management
    restart: 'always'
    container_name: backoffice_local_mq
    ports:
      - '5672:5672'
    networks:
      - djangonetwork


networks:
  djangonetwork:
      driver: bridge
